import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
// import { Roboto } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/Header";

import AppProvider from "./AppProvider";
import { cookies } from "next/headers";
import SlideSession from "@/components/SlideSession";
import accountApiRequests from "@/apiRequests/account";
import { AccountResType } from "@/schemaValidations/account.schema";

const inter = Inter({ subsets: ["vietnamese"] });

export const metadata: Metadata = {
  title: "Xay con tv",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const sessionToken = cookieStore.get("sessionToken")?.value || "";
  let user: AccountResType["data"] | null = null;
  if (sessionToken) {
    const data = await accountApiRequests.me(sessionToken);
    user = data.payload.data;
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className}`}>
        <Toaster />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AppProvider initialSessionToken={sessionToken} user={user}>
            <Header user={user} />
            {children}
            <SlideSession />
          </AppProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
